### ISSUE TITLE
[CSS] Add CSS variables for colors

### ISSUE THREAD

**Issue by totally-not-frito-lays** [codewithher/Web-C4C#12]
## About
Most of the CSS values are directly written into the CSS selectors. It's better practice to write these colors as a CSS variable. This makes it so that you can the value of the variable and it will reflect across all elements that use this.

You should be editing most of the CSS files, wherever there are CSS colors. Come up with a naming convention.

Variables should be placed at the top of the CSS sheet for ease of access and to setup global hierarchy.

Anything that qualifies under the `:root` selector should be placed within `global.css`

## Resources
- Learn more about [CSS variables at W3Schools](https://www.w3schools.com/css/css3_variables.asp)
- Pick good [variable names](https://youtu.be/-J3wNP6u5YU?si=0n9BiGTf0yPWKc0w)!
- Pick good [CSS variable names](https://www.fixate.it/blog/make-your-css-variable-names-suck-less)

## Expected result

It should look something like this:
> Before
```css
header {
  background-color: #356e7a;
}
/* ... */
.subheader {
  color: #356e7a;
}
```

> After
```css
:root {
  --text-header: #356e7a;
}
.header {
  background-color: var(--text-header);
}
/* ... */
.subheader {
  color: var(--text-header);
}
```

## Additional Notes
[CSS variables](https://caniuse.com/?search=css%20variables) are supported in the majority of modern browsers and are considered best practice in [web development](https://www.freecodecamp.org/news/what-are-css-variables-and-how-to-use-them/).
